services:
  daniszwarc:
    build: .
    container_name: daniszwarc
    restart: unless-stopped
    networks:
      - n8n_default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.daniszwarc.rule=Host(`daniszwarc.com`) || Host(`www.daniszwarc.com`)"
      - "traefik.http.routers.daniszwarc.entrypoints=websecure"
      - "traefik.http.routers.daniszwarc.tls=true"
      - "traefik.http.routers.daniszwarc.tls.certresolver=letsencrypt"
      - "traefik.http.services.daniszwarc.loadbalancer.server.port=80"

networks:
  n8n_default:
    external: true
